name: 🎉 Release Binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs: 
  release: 
    runs-on: ubuntu-latest-16-cores

    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with: 
          go-version: 1.21.x

      - uses: goreleaser/goreleaser-action@v4
        with: 
          args: "release --clean"
          version: latest
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SLACK_WEBHOOK: "${{ secrets.RELEASE_SLACK_WEBHOOK }}"
          DISCORD_WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
          DISCORD_WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"